config/routes.rb
Rails.application.routes.draw do
  resource :leaderboard, only:[:show]

  devise_for :users
  root to: "home#index"
  get '/history', to: 'home#history'
  get '/log',     to: 'home#log'

  resources :matches
end

app/models/match.rb
class Match < ActiveRecord::Base

  validates_presence_of :score_a
  validates_presence_of :score_b
  validate :scores_are_greater_than_21
  validate :is_winning_by_two_points


  belongs_to :user_a, class_name: 'User', foreign_key: 'user_a_id'
  belongs_to :user_b, class_name: 'User', foreign_key: 'user_b_id'

  def scores_are_greater_than_21
    errors.add(:scores_are_greater_than_21,'One of the scores needs to be greater than 21') unless check_if_scores_are_greater_than_21
  end

  def is_winning_by_two_points
    errors.add(:two_points_advantage,"You don't have a two point advantage") unless wins_by_two_points
  end

  def check_if_scores_are_greater_than_21
    return false if self.score_a == nil or self.score_b == nil
    if self.score_a >= 21 or score_b >=21
      return true
    else
      return false
    end
  end

  def wins_by_two_points
    return false if self.score_a == nil or self.score_b == nil

    total = self.score_a - self.score_b
    if total.abs >= 2
      return true
    else
      return false
    end
  end

  def winner
    if wins_by_two_points
      if (self.score_a > self.score_b)
        user_a
      else
        user_b
      end
    else
      return "You don't have a winner"
    end
  end

  def looser
    if wins_by_two_points
      if (self.score_a > self.score_b)
        user_b
      else
        user_a
      end
    else
      return "You don't have a looser"
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :trackable, :validatable

  has_many :matches
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def history
  end

  def log
  end
end

app/controllers/leaderboards_controller.rb
class LeaderboardsController < ApplicationController
  def show
    @leaderboard = User.order(score: :desc)
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  include MatchesHelper

  def index
    @matches = Match.where(user_a_id: current_user.id)
  end

  def new
    @user_id = current_user.id
    @matches = Match.new
  end

  def create
    new_match = Match.create(match_params)
    if new_match.persisted?
      winner = new_match.winner
      looser = new_match.looser

      rank_difference = winner.rank - looser.rank
      scoreTotal = 100 + calculateBonus(rank_difference)

      winner.increment!(:score,scoreTotal)
      winner.increment!(:games_played)
      looser.increment!(:games_played)

      reorder_ranks

      flash[:notice] = "Successfully created..."
      redirect_to matches_path
    else
      flash[:notice] = "Problems #{new_match.errors.full_messages}"

      render action: :new, :status => 422
    end
  end

  private
  def match_params
    params.require(:match).permit(:date,:user_a_id,:user_b_id,:score_a,:score_b)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leaderboards_helper.rb
module LeaderboardsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper

  def calculateBonus rank_difference
    bonus = 0

    if rank_difference > 0
      bonus = User.count/rank_difference.to_f
    elsif rank_difference < 0
      bonus = rank_difference.to_f * User.count
    end

    totalBonus = bonus.abs.floor.to_i
    totalBonus
  end

  def reorder_ranks
    leaderboard = User.order(score: :desc)
    leaderboard.each_with_index do |player,index|
      player.update({rank: index +1})
    end
  end
end

app/views/home/history.html.erb
<h1 class='page-header'>History</h1>

<div class="alert alert-warning" role="alert">This is a sample page. Replace link in the header with your own.</div>

<%= image_tag('history.png') %>

app/views/home/index.html.erb
<h1>Navigate with the menu above</h1>

app/views/home/log.html.erb
<h1 class='page-header'>Log Game</h1>

<div class="alert alert-warning" role="alert">This is a sample page. Replace link in the header with your own.</div>

<%= image_tag('log_game.png') %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Pingpong</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Leadboard', leaderboard_path %></li>

        <% if user_signed_in? %>
          <li><%= link_to 'New Match', new_match_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'History',matches_path %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

<div class="alert alert-default">
  <%= flash[:notice] %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pingpong Leaderboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css", integrity: "sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js", integrity: "sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class='container'>
    <%= yield %>
  </div>
</body>
</html>

app/views/leaderboards/show.html.erb
<h1>Leaderboad</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>
        Rank
      </th>
      <th>
        Email
      </th>
      <th>
        Score
      </th>
      <th>
        Games Played
      </th>
    </tr>
  </thead>

  <tbody>

    <% @leaderboard.each do |player| %>
      <tr>
        <th><%= player.rank %></th>
        <th><%= player.email %></th>
        <th><%= player.score %></th>
        <th><%= player.games_played %></th>
      </tr>
    <% end %>

  </tbody>
</table>

app/views/matches/index.html.erb
<h1>My Matches</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>
        id
      </th>
      <th>
        Oponent
      </th>
      <th>
        Your score
      </th>
      <th>
        Oponents score
      </th>
      <th>
        Date
      </th>
    </tr>
  </thead>

  <tbody>

    <% @matches.each do |match| %>
      <tr>
        <th><%= match.id %></th>
        <th><%= match.user_b.email %></th>
        <th><%= match.score_a %></th>
        <th><%= match.score_b %></th>
        <th><%= match.date %></th>

      </tr>
    <% end %>

  </tbody>
</table>

app/views/matches/new.html.erb
<h1>Create Match</h1>

<%= form_for @matches do |f| %>
  <%= f.date_select :date %>
  <%= f.label :date %>

  <%= f.hidden_field  :user_a_id, value: @user_id %>

  <%= f.label :Oponent %>
  <%= f.collection_select :user_b_id, User.all, :id, :email %>

  <%= f.label :your_score %>
  <%= f.text_field :score_a %>

  <%= f.label :oponents_score %>
  <%= f.text_field :score_b %>

  <%= f.submit %>

<% end %>